# Ohuseire.ee andmete uurimiseks

Vaatluse all on ohuseire.ee APIst saadud andmed:
- `stations.json`
- `indicators.json`

Eesmärk on näha:
- millised jaamad on olemas,
- kus need asuvad,
- milliseid indikaatoreid mõõdetakse,
- millised näitajad võiksid sobida võrdluseks Open-Meteo andmetega.

In [1]:
import json
import ast
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

In [4]:
base = Path.cwd().parent

stations_csv = base / "data" / "processed" / "ohuseire" / "stations.csv"
indicators_csv = base / "data" / "processed" / "ohuseire" / "indicators.csv"

stations = pd.read_csv(stations_csv)
indicators = pd.read_csv(indicators_csv)


print(stations.shape)
print(indicators.shape)

(17, 10)
(46, 6)

In [6]:
stations.head(10)

,id,type,geometry.coordinates,geometry.type,properties.type,properties.name,properties.description,properties.image,properties.airviro_code,properties.indicators
0,3,Feature,"[25.928164, 59.515308]",Point,BACKGROUND,Lahemaa,<p>Lahemaa seirejaam paikneb Palmse m&otilde;i...,NaN,S04,"[1, 3, 4, 6, 13, 23, 34, 37, 41]"
1,9,Feature,"[21.844596, 58.376235]",Point,BACKGROUND,Vilsandi,<p>Vilsandi seirejaam paikneb Saaremaast l&aum...,images/stations/vilsandi.jpg,S09,"[1, 3, 6, 23, 34, 37, 41, 81, 82]"
2,10,Feature,"[26.503401, 58.727153]",Point,BACKGROUND,Saarejärve,<p>Saarej&auml;rve seirejaam paikneb J&otilde;...,NaN,S08,"[1, 3, 6, 23, 34, 37, 41]"
3,33,Feature,"[24.925486, 58.52445]",Point,BACKGROUND,Tahkuse,<p>Tahkuse seirejaam paikneb Soomaal alates 19...,NaN,S31,"[1, 3, 6, 11, 68, 69]"
4,11,Feature,"[24.931303, 59.493664]",Point,INDUSTRY,Muuga 1,<p>Muuga 1 seirejaam on paigaldatud Muuga Sada...,NaN,S11,"[8, 11, 34, 37, 41]"
5,16,Feature,"[24.066607, 59.343843]",Point,INDUSTRY,Paldiski,<p>Paldiski seirejaam asub Pakri poolsaarel Al...,images/stations/paldiski.jpg,S23,"[8, 14, 16, 18, 34, 37, 41]"
6,21,Feature,"[27.750225, 59.40276]",Point,INDUSTRY,Sillamäe,<p>Sillam&auml;e seirejaam on paigaldatud Sill...,images/stations/sillamae.jpg,S30,"[8, 10, 11, 14, 16, 18, 20, 21, 23, 34, 37, 41]"
7,38,Feature,"[27.870776, 59.375311]",Point,INDUSTRY,Sinimäe,<p>Sinim&auml;e seirejaam paikneb Sinim&auml;e...,NaN,S32,"[1, 8, 11, 21, 23, 31, 34, 37, 41]"
8,40,Feature,"[27.244931, 59.393961]",Point,INDUSTRY,VKG,<p>VKG seirejaam paikneb VKG tootmisterritoori...,NaN,S18,"[1, 11, 34, 37, 41]"
9,41,Feature,"[27.748683, 59.39384]",Point,INDUSTRY,Sillamäe 2,<p>Sillam&auml;e seirejaam on paigaldatud Sill...,NaN,S33,"[10, 34, 37, 41]"

In [7]:
indicators.head(10)

,id,name,formula,unit,description,levels
0,1,Vääveldioksiid,SO<sub>2</sub>,µg/m3,Vääveldioksiid eraldub välisõhku valdavalt vää...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
1,3,Lämmastikdioksiid,NO<sub>2</sub>,µg/m3,Välisõhku satub lämmastikdioksiid põlemisprots...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
2,4,Süsinikoksiid,CO,mg/m3,Süsinikoksiid ehk vingugaas tekib süsinikku si...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
3,6,Osoon,O<sub>3</sub>,µg/m3,Maapinnalähedane (troposfääri) osoon moodustub...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
4,8,Lenduvad orgaanilised ühendid,NMHC,µg/m3,Lenduvad orgaanilised ühendid ehk LOÜ (volatil...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
5,10,Ammoniaak,NH<sub>3</sub>,ug/m3,"Ammoniaak on terava ja ärritava lõhnaga gaas, ...","[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
6,11,Vesiniksulfiid,H<sub>2</sub>S,ug/m3,Vesiniksulfiid on ebameeldiva lõhnaga (mädamun...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
7,13,Elavhõbe,Hg,ng/m3,Elavhõbe esineb välisõhus gaasilisel kujul. El...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
8,14,Benseen,C<sub>6</sub>H<sub>6</sub>,µg/m3,Benseen on lihtsaima struktuuriga aromaatne sü...,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."
9,16,Tolueen,C<sub>7</sub>H<sub>8</sub>,µg/m3,NaN,"[{'id': 5, 'code': 'LEVEL_5', 'name': 'Väga ha..."

In [8]:
stations.columns.tolist()

['id',
 'type',
 'geometry.coordinates',
 'geometry.type',
 'properties.type',
 'properties.name',
 'properties.description',
 'properties.image',
 'properties.airviro_code',
 'properties.indicators']

In [9]:
indicators.columns.tolist()

['id', 'name', 'formula', 'unit', 'description', 'levels']

In [10]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       17 non-null     int64
 1   type                     17 non-null     str
 2   geometry.coordinates     17 non-null     str
 3   geometry.type            17 non-null     str
 4   properties.type          17 non-null     str
 5   properties.name          17 non-null     str
 6   properties.description   17 non-null     str
 7   properties.image         7 non-null      str
 8   properties.airviro_code  17 non-null     str
 9   properties.indicators    17 non-null     str
dtypes: int64(1), str(9)
memory usage: 1.5 KB

In [11]:
indicators.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           46 non-null     int64
 1   name         46 non-null     str
 2   formula      46 non-null     str
 3   unit         46 non-null     str
 4   description  37 non-null     str
 5   levels       25 non-null     str
dtypes: int64(1), str(5)
memory usage: 2.3 KB

Palju jaamu on tüübi järgi:

In [12]:
stations["properties.type"].value_counts()

properties.type
INDUSTRY      7
URBAN         6
BACKGROUND    4
Name: count, dtype: int64


Mitu erinevvat indikaatorit on?

In [13]:
print("Indikaatoreid kokku:", indicators["id"].nunique())

Indikaatoreid kokku: 46

In [16]:
indicators[["id", "name", "formula", "unit"]].head(47)

,id,name,formula,unit
0,1,Vääveldioksiid,SO<sub>2</sub>,µg/m3
1,3,Lämmastikdioksiid,NO<sub>2</sub>,µg/m3
2,4,Süsinikoksiid,CO,mg/m3
3,6,Osoon,O<sub>3</sub>,µg/m3
4,8,Lenduvad orgaanilised ühendid,NMHC,µg/m3
5,10,Ammoniaak,NH<sub>3</sub>,ug/m3
6,11,Vesiniksulfiid,H<sub>2</sub>S,ug/m3
7,13,Elavhõbe,Hg,ng/m3
8,14,Benseen,C<sub>6</sub>H<sub>6</sub>,µg/m3
9,16,Tolueen,C<sub>7</sub>H<sub>8</sub>,µg/m3
10,18,Ksüleen,C<sub>8</sub>H<sub>10</sub>,µg/m3
11,20,TSP,TSP,mg/m3
12,21,Peened osakesed,PM10,µg/m3
13,23,Eriti peened osakesed,PM2.5,µg/m3
14,25,Temperatuuride erinevus 2 m ja 8 m vahel,T<sub>DIFF08</sub>,deg.C
15,26,Temperatuuride erinevus 8 m ja 22 m vahel,T<sub>DIFF22</sub>,deg.C
16,27,Päikesekiirgus,RAD,W/m2
17,28,Õhurõhk,PRESS,hPa
18,29,Õhurõhk,PRESS,hPa
19,30,Sademed,RAIN,mm/day
20,31,Suhteline õhuniiskus,HUM,%
21,32,Suhteline õhuniiskus,HUM,%
22,33,Temperatuur,TEMP,deg.C
23,34,Temperatuur,TEMP,deg.C
24,37,Tuule suund 10 m kõrgusel,WD<sub>10</sub>,Deg °
25,38,Tuule suund 24 m kõrgusel,WD<sub>24</sub>,Deg °
26,41,Tuule kiirus 10 m kõrgusel,WS<sub>10</sub>,m/s
27,42,Tuule kiirus 24 m kõrgusel,WS<sub>24</sub>,m/s
28,64,Tuule suund 30 m kõrgusel,WD<sub>30</s,Deg °
29,65,Tuule kiirus 30 m kõrgusel,WS<sub>30</s,m/s
30,66,Temperatuur 10 m kõrgusel,TEMP<sub>10<,deg.C
31,67,Temperatuur 30 m kõrgusel,TEMP<sub>30<,deg.C
32,68,Süsinikdioksiid,dry CO2,ppm
33,69,Süsinikdioksiid,wet CO2,ppm
34,70,Süsinikdioksiid,CO2,ppm
35,71,Metaan,CH4,ppm
36,72,Dilämmastikoksiid,N2O,ppm
37,73,Vääveldioksiid,SO<sub>2</sub>,µg/m3
38,74,Lämmastikdioksiid,NO<sub>2</sub>,µg/m3
39,75,Süsinikoksiid,CO,mg/m3
40,76,Vesiniksulfiid,H<sub>2</sub>S,ug/m3
41,77,Peened osakesed,PM10,µg/m3
42,78,Eriti peened osakesed,PM25,µg/m3
43,79,Must süsinik,BC,ug/m3
44,81,UV-A kiirgus,UV-A,W/m2
45,82,UV-B kiirgus,UV-B,W/m2